version: "3.9"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        restart: always
        ports:
            - "3000:5173"
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./backend/.env
        depends_on:
            - db
        ports:
            - "9999:9999"
    db:
        image: postgres:15
        env_file:
            - ./backend/.env
        restart: always
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
